### ISSUE TITLE
feature request: a real / command 

### ISSUE THREAD

**Issue by Megagalatkikarea2** [SHOEGAZEssb/AchManager#1]
![image_2024-05-09_015121759](https://github.com/SHOEGAZEssb/AchManager/assets/13068903/414ed908-f738-4bc4-9220-091648620224)
change /pmycommand to an actual short command like /achievements or /achv /pach

**Comment by Megagalatkikarea2** [comment]
or better yet an option in general config to open when the achievements window opens

**Comment by SHOEGAZEssb** [comment]
commands added in v0.0.0.5
